version: '3'

services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=bobur
      - POSTGRES_PASSWORD=Qwerty123
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis

  celery:
    build: .
    command: celery -A Ecommerce worker -l INFO

    depends_on:
      - web
      - redis
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5555:5555'
    command: "celery -A Ecommerce flower --address=0.0.0.0"
    depends_on:
      - celery

volumes:
  pgdata: