version: '3'

services:
  web:
    build: .
    container_name: web
    command: gunicorn Ecommerce.wsgi:application --bind 0.0.0.0:8000
    expose:
        - 8000
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=bobur
      - POSTGRES_PASSWORD=Qwerty123
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

  celery:
    build: .
    command: celery -A Ecommerce worker -l INFO
    restart: unless-stopped
    depends_on:
      - web
      - redis
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5555
    command: "celery -A Ecommerce flower --address=0.0.0.0"
    depends_on:
      - celery
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  pgdata: